session_name: dotfiles
windows:
  - window_name: vim
    panes:
    - shell_command:
      - reset
      - vim
      - :Ex
      focus: true
  - window_name: docs
    panes:
    - vim README.md
  - window_name: git
    panes:
    - git status
