session_name: dev
windows:
- window_name: dev
  layout: main-vertical
  panes:
    - shell_command:
      - reset
      - vim
      - :f html
      - :set syntax=html
      - :vnew
      - :f css
      - :set syntax=css
      - :vnew
      - :f js
      - :set syntax=javascript
- window_name: compass
  panes:
    - shell_command:
      - compass -v
